# Generated by Django 3.0.3 on 2020-02-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricant_name', models.CharField(max_length=120)),
                ('fabricant_logo', models.ImageField(upload_to='fabricants-logos')),
            ],
        ),
    ]
